### PR TITLE
Upgrade to sha256

### PR DESCRIPTION
**Pull request by fauvel**
@njam fyi

### CODE REVIEW

**Comment by fauvel** [comment]
@tomaszdurka please review

**Comment by fauvel** [comment]
@tomaszdurka looks like @ppp0 has done [exactly the same PR](https://github.com/cargomedia/homebrew-cargomedia/pull/16) one month ago... Please review quickly!

**Comment by ppp0** [comment]
Oh, I already had forgotten!

**Comment by ppp0** [comment]
looks very good to me!

**Pull request merged**
