### PR TITLE
SHA1 mismatch for github-issues

### PR DESCRIPTION
**Pull request by tomaszdurka**
As reported by @NicolasSchmutz

### CODE REVIEW

**Comment by tomaszdurka** [comment]
This is quite strange. I've looked through Formula history and seems I've adjusted sha1 one well. Additionally this working some time ago (e.g. when I've installed it on Macmini). Did github changed something in the way they archive things?

**Comment by tomaszdurka** [comment]
@njam Please review

**Comment by njam** [comment]
I get a different sha?
```
$ curl -s https://github.com/cargomedia/github-issues/archive/1.2.zip | shasum -
39f62752a0df5d84e240b1f1d85bdf96eacfa649  -
```

**Comment by tomaszdurka** [comment]
I think you need to follow redirects.

```
$ curl -Ls https://github.com/cargomedia/github-issues/archive/1.2.zip | shasum -
aaf11d2be8dff5d2ce59206c831498466dc0dd64  -
```

**Comment by njam** [comment]
:dizzy_face: lgtm

**Pull request merged**
